# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 299)
        MainWindow.setStyleSheet("background-image: url(:/img/resourcesFiles/bg.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.stackedWidget.setStyleSheet("background:transparent;\n"
"color:white")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.timeLabel = QtWidgets.QLabel(self.page)
        self.timeLabel.setGeometry(QtCore.QRect(65, 75, 251, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(39)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color:white")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(140, 75, 21, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(230,230,230)")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(225, 75, 21, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(230,230,230)")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(197, 135, 173, 131))
        self.frame_2.setStyleSheet("background-color:rgba(0,0,0,120);\n"
"border :1px solid transparent;\n"
"border-radius : 7px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(8, 11, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:transparent")
        self.label_11.setObjectName("label_11")
        self.tmp_str = QtWidgets.QLabel(self.frame_2)
        self.tmp_str.setGeometry(QtCore.QRect(90, 87, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tmp_str.setFont(font)
        self.tmp_str.setStyleSheet("background:transparent")
        self.tmp_str.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_str.setObjectName("tmp_str")
        self.tmp_val = QtWidgets.QLabel(self.frame_2)
        self.tmp_val.setGeometry(QtCore.QRect(95, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tmp_val.setFont(font)
        self.tmp_val.setStyleSheet("background:transparent")
        self.tmp_val.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_val.setObjectName("tmp_val")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(133, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background:transparent")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_4.setGeometry(QtCore.QRect(10, 40, 81, 81))
        self.stackedWidget_4.setStyleSheet("")
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_4.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_4.addWidget(self.page_8)
        self.nextButton = QtWidgets.QPushButton(self.page)
        self.nextButton.setGeometry(QtCore.QRect(343, 10, 27, 27))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 ExtraBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;}\n"
"QPushButton:pressed{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.nextButton.setObjectName("nextButton")
        self.dateLabel = QtWidgets.QLabel(self.page)
        self.dateLabel.setGeometry(QtCore.QRect(95, 35, 191, 41))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("color:white")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.stackedDust = QtWidgets.QStackedWidget(self.page)
        self.stackedDust.setGeometry(QtCore.QRect(10, 135, 181, 131))
        self.stackedDust.setObjectName("stackedDust")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame = QtWidgets.QFrame(self.page_5)
        self.frame.setGeometry(QtCore.QRect(0, 0, 173, 131))
        self.frame.setStyleSheet("background-color:rgba(0,0,0,120);\n"
"border :1px solid transparent;\n"
"border-radius : 7px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(8, 11, 91, 21))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background:transparent")
        self.label_9.setObjectName("label_9")
        self.dust_str = QtWidgets.QLabel(self.frame)
        self.dust_str.setGeometry(QtCore.QRect(95, 87, 71, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dust_str.setFont(font)
        self.dust_str.setStyleSheet("background:transparent")
        self.dust_str.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_str.setObjectName("dust_str")
        self.dust_val = QtWidgets.QLabel(self.frame)
        self.dust_val.setGeometry(QtCore.QRect(90, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dust_val.setFont(font)
        self.dust_val.setStyleSheet("background:transparent")
        self.dust_val.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_val.setObjectName("dust_val")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 40, 81, 81))
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.nextDust = QtWidgets.QPushButton(self.frame)
        self.nextDust.setGeometry(QtCore.QRect(140, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nextDust.setFont(font)
        self.nextDust.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;\n"
"background:transparent;}\n"
"QPushButton:pressed{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.nextDust.setObjectName("nextDust")
        self.stackedDust.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.frame_3 = QtWidgets.QFrame(self.page_6)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 173, 131))
        self.frame_3.setStyleSheet("background-color:rgba(0,0,0,120);\n"
"border :1px solid transparent;\n"
"border-radius : 7px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(8, 11, 91, 21))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:transparent")
        self.label_10.setObjectName("label_10")
        self.dust_str_2 = QtWidgets.QLabel(self.frame_3)
        self.dust_str_2.setGeometry(QtCore.QRect(95, 87, 71, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dust_str_2.setFont(font)
        self.dust_str_2.setStyleSheet("background:transparent")
        self.dust_str_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_str_2.setObjectName("dust_str_2")
        self.dust_val_2 = QtWidgets.QLabel(self.frame_3)
        self.dust_val_2.setGeometry(QtCore.QRect(90, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dust_val_2.setFont(font)
        self.dust_val_2.setStyleSheet("background:transparent")
        self.dust_val_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_val_2.setObjectName("dust_val_2")
        self.stackedWidget_5 = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget_5.setGeometry(QtCore.QRect(10, 40, 81, 81))
        self.stackedWidget_5.setStyleSheet("")
        self.stackedWidget_5.setObjectName("stackedWidget_5")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.stackedWidget_5.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.stackedWidget_5.addWidget(self.page_10)
        self.backDust = QtWidgets.QPushButton(self.frame_3)
        self.backDust.setGeometry(QtCore.QRect(140, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.backDust.setFont(font)
        self.backDust.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;\n"
"background:transparent;}\n"
"QPushButton:pressed{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.backDust.setObjectName("backDust")
        self.stackedDust.addWidget(self.page_6)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 45, 359, 191))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background:rgba(0,0,0,120);\n"
"color:white;\n"
"gridline-color:white;/*rgba(0,0,0,120);*/\n"
"border:transparent;\n"
"border-radius:2px;\n"
"selection-background-color: white;\n"
"selection-color:black}\n"
"QTableView\n"
"{\n"
"border:transparent;\n"
"}\n"
"QHeaderView::section{\n"
"color:black;\n"
"background-color:white;\n"
"border:transparent;\n"
"border-radius:2px\n"
"}\n"
"QScrollBar::horizontal {\n"
"height:7px;\n"
"border: transparent;\n"
"background:transparent;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"background: transparent;\n"
"}\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"background: transparent;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: white;\n"
"border-radius:2px;\n"
"margin : 0px 2px 2px 2px}\n"
"\n"
"")
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Light")
        font.setPointSize(11)
        font.setUnderline(False)
        font.setKerning(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(26)
        self.tableWidget.verticalHeader().setDefaultSectionSize(26)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        self.delButton = QtWidgets.QPushButton(self.page_2)
        self.delButton.setGeometry(QtCore.QRect(343, 10, 27, 27))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.delButton.setFont(font)
        self.delButton.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;}\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.delButton.setCheckable(True)
        self.delButton.setObjectName("delButton")
        self.addButton = QtWidgets.QPushButton(self.page_2)
        self.addButton.setGeometry(QtCore.QRect(308, 10, 27, 27))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;}\n"
"QPushButton::checked{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.addButton.setCheckable(True)
        self.addButton.setObjectName("addButton")
        self.backButton = QtWidgets.QPushButton(self.page_2)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 27, 27))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 ExtraBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;}\n"
"QPushButton:pressed{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.backButton.setObjectName("backButton")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 242, 153, 29))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(10)
        font.setUnderline(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.showDialog = QtWidgets.QPushButton(self.page_2)
        self.showDialog.setGeometry(QtCore.QRect(320, 242, 21, 29))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.showDialog.setFont(font)
        self.showDialog.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;\n"
"background:transparent;}\n"
"QPushButton:pressed{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.showDialog.setObjectName("showDialog")
        self.uploadButton = QtWidgets.QPushButton(self.page_2)
        self.uploadButton.setGeometry(QtCore.QRect(348, 242, 21, 29))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uploadButton.setFont(font)
        self.uploadButton.setStyleSheet("QPushButton{border:2px solid white;\n"
"border-radius : 7px;\n"
"background:transparent;}\n"
"QPushButton:pressed{\n"
"background-color:white;\n"
"color:rgb(90,90,90);\n"
"border:2px solid white;\n"
"border-radius : 7px;}")
        self.uploadButton.setObjectName("uploadButton")
        self.timeEdit = QtWidgets.QTimeEdit(self.page_2)
        self.timeEdit.setGeometry(QtCore.QRect(52, 243, 101, 29))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(11)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("selection-color : white;\n"
"selection-background-color : black;\n"
"border:transparent;")
        self.timeEdit.setObjectName("timeEdit")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(12, 243, 41, 29))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Regular")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"color:white;\n"
"selection-color : white;\n"
"selection-background-color : black;\n"
"}\n"
"QComboBoxt::down-button {\n"
"color:white;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 242, 143, 29))
        self.label.setStyleSheet("QLabel{border:2px solid white;\n"
"border-radius : 7px;}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.tableWidget.raise_()
        self.delButton.raise_()
        self.addButton.raise_()
        self.backButton.raise_()
        self.lineEdit.raise_()
        self.showDialog.raise_()
        self.uploadButton.raise_()
        self.timeEdit.raise_()
        self.comboBox.raise_()
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_4.setCurrentIndex(0)
        self.stackedDust.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeLabel.setText(_translate("MainWindow", "00  00  00"))
        self.label_2.setText(_translate("MainWindow", ":"))
        self.label_4.setText(_translate("MainWindow", ":"))
        self.label_11.setText(_translate("MainWindow", "날씨"))
        self.tmp_str.setText(_translate("MainWindow", "구름많음"))
        self.tmp_val.setText(_translate("MainWindow", "- 90"))
        self.label_14.setText(_translate("MainWindow", "℃"))
        self.nextButton.setText(_translate("MainWindow", ">"))
        self.dateLabel.setText(_translate("MainWindow", "2019년  12월  31일  "))
        self.label_9.setText(_translate("MainWindow", "미세먼지"))
        self.dust_str.setText(_translate("MainWindow", "매우나쁨"))
        self.dust_val.setText(_translate("MainWindow", "100"))
        self.nextDust.setText(_translate("MainWindow", ">"))
        self.label_10.setText(_translate("MainWindow", "초미세먼지"))
        self.dust_str_2.setText(_translate("MainWindow", "매우나쁨"))
        self.dust_val_2.setText(_translate("MainWindow", "130"))
        self.backDust.setText(_translate("MainWindow", "<"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", " 월 "))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", " 화 "))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", " 수 "))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", " 목 "))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", " 금 "))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", " 토 "))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", " 일 "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "오전"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "오후"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "(6:30)아침점호"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.delButton.setText(_translate("MainWindow", "-"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.backButton.setText(_translate("MainWindow", "<"))
        self.showDialog.setText(_translate("MainWindow", "..."))
        self.uploadButton.setText(_translate("MainWindow", "↑"))
        self.comboBox.setItemText(0, _translate("MainWindow", "월"))
        self.comboBox.setItemText(1, _translate("MainWindow", "화"))
        self.comboBox.setItemText(2, _translate("MainWindow", "수"))
        self.comboBox.setItemText(3, _translate("MainWindow", "목"))
        self.comboBox.setItemText(4, _translate("MainWindow", "금"))
        self.comboBox.setItemText(5, _translate("MainWindow", "토"))
        self.comboBox.setItemText(6, _translate("MainWindow", "일"))

import resources_rc
